services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user      # Define o nome de usuário
      POSTGRES_PASSWORD: pass    # Define a senha do usuário
      POSTGRES_DB: db_postgres # Define o nome do banco de dados
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata:
